# Generated by Django 4.1.7 on 2023-03-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_blogpost_likes_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_Unlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('post_id', models.CharField(max_length=255)),
                ('is_like', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
    ]
